import React, { useEffect, useState } from 'react';
import { 
  subscribePushDebugLogs, 
  clearPushDebugLogs, 
  PushDebugLog, 
  validatePushNotificationPayload, 
  addPushDebugLog,
  checkNotificationPermission
} from '../lib/pushNotifications';
import { 
  Terminal, 
  CheckCircle2, 
  AlertTriangle, 
  Trash2, 
  ShieldAlert, 
  Bug, 
  RefreshCw, 
  ChevronDown, 
  ChevronUp, 
  Info, 
  Sparkles,
  Layers
} from 'lucide-react';

interface NativePushDebuggerProps {
  uid?: string;
  oneSignalSubscriptionId?: string;
}

export const NativePushDebugger: React.FC<NativePushDebuggerProps> = ({ uid, oneSignalSubscriptionId }) => {
  const [logs, setLogs] = useState<PushDebugLog[]>([]);
  const [expandedLogIdx, setExpandedLogIdx] = useState<number | null>(null);
  const [testPayload, setTestPayload] = useState({
    senderId: 'debug_node_fara',
    content: 'Enrypted tunnel handshake synchronization sequence complete.',
    timestamp: Date.now(),
    title: 'TUNNEL HANDSHAKE',
    tag: 'cipher-sync'
  });
  const [validationResult, setValidationResult] = useState<{
    valid: boolean | null;
    errors?: string;
  }>({ valid: null });

  useEffect(() => {
    // Subscribe to real-time events generated by OneSignal/FCM registration & dispatches
    const unsubscribe = subscribePushDebugLogs((newLogs) => {
      setLogs(newLogs);
    });
    return () => unsubscribe();
  }, []);

  const handleClearLogs = () => {
    clearPushDebugLogs();
    setExpandedLogIdx(null);
  };

  const handleTestValidator = () => {
    try {
      const isValid = validatePushNotificationPayload(testPayload);
      if (isValid) {
        setValidationResult({
          valid: true
        });
      } else {
        setValidationResult({
          valid: false,
          errors: 'Schema validator rejected fields. Check logs for details.'
        });
      }
    } catch (err: any) {
      setValidationResult({
        valid: false,
        errors: err.message || String(err)
      });
    }
  };

  const currentPermission = checkNotificationPermission();

  return (
    <div id="native-push-debugger-root" className="border border-[var(--neon-green)]/20 bg-black/90 p-4 font-mono select-text w-full">
      {/* Title Header */}
      <div className="flex items-center justify-between border-b border-[var(--neon-green)]/20 pb-3 mb-4">
        <div className="flex items-center space-x-2">
          <Terminal className="w-4 h-4 text-[var(--neon-green)] animate-pulse" />
          <span className="text-xs font-bold tracking-widest text-[var(--neon-green)] uppercase">
            Native Push Debugger & Diagnostic Logs
          </span>
        </div>
        <div className="flex items-center space-x-2">
          <span className="text-[9px] px-1.5 py-0.5 bg-[var(--neon-green)]/15 text-[var(--neon-green)] rounded-none border border-[var(--neon-green)]/35">
            PWA SANDBOX
          </span>
        </div>
      </div>

      {/* Grid of details */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-[10px] mb-4">
        <div className="border border-zinc-900 p-2.5 bg-black/50 space-y-2">
          <div className="text-[var(--neon-green)] uppercase text-[9px] tracking-wide font-extrabold flex items-center mb-1">
            <Layers className="w-3.5 h-3.5 mr-1" /> Core Service Specs
          </div>
          <div className="flex justify-between border-b border-zinc-950 pb-1">
            <span className="text-zinc-550">UID:</span>
            <span className="text-zinc-300 truncate max-w-[170px]">{uid || "NOT LOGGED IN"}</span>
          </div>
          <div className="flex justify-between border-b border-zinc-950 pb-1">
            <span className="text-zinc-550">OneSignal Sub ID:</span>
            <span className={oneSignalSubscriptionId ? "text-[var(--neon-green)] font-bold truncate max-w-[170px]" : "text-zinc-500"}>
              {oneSignalSubscriptionId || "UNREGISTERED"}
            </span>
          </div>
          <div className="flex justify-between">
            <span className="text-zinc-550">Permission:</span>
            <span className={`px-1 text-[9px] font-bold ${
              currentPermission === 'granted' ? 'bg-[var(--neon-green)]/10 text-[var(--neon-green)]' :
              currentPermission === 'denied' ? 'bg-red-950 text-red-400' : 'bg-yellow-950 text-yellow-400'
            }`}>
              {currentPermission.toUpperCase()}
            </span>
          </div>
        </div>

        <div className="border border-zinc-900 p-2.5 bg-black/50 space-y-2 flex flex-col justify-between">
          <div className="text-[var(--neon-green)] uppercase text-[9px] tracking-wide font-extrabold flex items-center mb-1">
            <Bug className="w-3.5 h-3.5 mr-1" /> Payload Schema Validator
          </div>
          <div className="space-y-1.5">
            <div className="flex flex-col gap-1 text-[9px]">
              <span className="text-zinc-500">Local testing properties:</span>
              <div className="grid grid-cols-3 gap-1">
                <input 
                  type="text" 
                  value={testPayload.senderId}
                  placeholder="senderId"
                  onChange={e => setTestPayload(p => ({ ...p, senderId: e.target.value }))}
                  className="bg-zinc-950 border border-zinc-900 px-1 py-0.5 text-white max-w-full focus:outline-none focus:border-[var(--neon-green)]/50"
                />
                <input 
                  type="text" 
                  value={testPayload.content}
                  placeholder="content"
                  onChange={e => setTestPayload(p => ({ ...p, content: e.target.value }))}
                  className="bg-zinc-950 border border-zinc-900 px-1 py-0.5 text-white col-span-2 focus:outline-none focus:border-[var(--neon-green)]/50"
                />
              </div>
            </div>
            
            {/* Validation outcome */}
            {validationResult.valid !== null && (
              <div className={`p-1 text-[8px] flex items-center gap-1 ${
                validationResult.valid ? 'bg-emerald-950/40 text-[var(--neon-green)] border border-[var(--neon-green)]/30' : 'bg-red-950/40 text-red-400 border border-red-500/30'
              }`}>
                {validationResult.valid ? (
                  <>
                    <CheckCircle2 className="w-3 h-3 text-[var(--neon-green)] shrink-0" />
                    <span>SCHEMA INTEGRITY SECURED</span>
                  </>
                ) : (
                  <>
                    <ShieldAlert className="w-3 h-3 text-red-450 shrink-0" />
                    <span className="truncate">{validationResult.errors || "Invalid payload."}</span>
                  </>
                )}
              </div>
            )}
          </div>

          <button
            type="button"
            onClick={handleTestValidator}
            className="w-full text-center py-1 bg-black border border-[var(--neon-green)]/30 hover:border-[var(--neon-green)] text-white hover:bg-[var(--neon-green)]/15 text-[9px] uppercase tracking-wider transition cursor-pointer"
          >
            Validate Payload Schema
          </button>
        </div>
      </div>

      {/* Terminal logs list */}
      <div className="space-y-1.5">
        <div className="flex justify-between items-center text-[10px] text-zinc-550 uppercase mb-1">
          <span className="flex items-center">
            <Sparkles className="w-3 h-3 mr-1 text-[var(--neon-green)]" /> Output Logs Trace ({logs.length})
          </span>
          {logs.length > 0 && (
            <button 
              type="button" 
              onClick={handleClearLogs}
              className="text-zinc-650 hover:text-red-400 transition flex items-center space-x-1.5 uppercase text-[9px]"
            >
              <Trash2 className="w-3 h-3 mr-0.5" />
              <span>Clear</span>
            </button>
          )}
        </div>

        {logs.length === 0 ? (
          <div className="border border-zinc-950 bg-black/40 p-4 text-center text-zinc-650 text-[10px] uppercase">
            No pipeline events observed. Run diagnostic sync to populate telemetry traces.
          </div>
        ) : (
          <div className="bg-zinc-950/90 border border-zinc-900 rounded-none max-h-52 overflow-y-auto divide-y divide-zinc-950 scrollbar-thin">
            {logs.map((log, idx) => {
              const LogIcon = log.type === 'error' ? AlertTriangle :
                              log.type === 'success' ? CheckCircle2 :
                              log.type === 'token' ? Sparkles : Info;
              
              const typeColor = log.type === 'error' ? 'text-red-400' :
                                log.type === 'success' ? 'text-[var(--neon-green)]' :
                                log.type === 'token' ? 'text-cyan-400' : 'text-zinc-400';

              const isExpanded = expandedLogIdx === idx;

              return (
                <div key={idx} className="bg-black/20 text-[9px] font-mono leading-normal">
                  <div 
                    onClick={() => setExpandedLogIdx(isExpanded ? null : idx)}
                    className="flex items-center justify-between p-2 cursor-pointer hover:bg-zinc-900/40 select-none transition"
                  >
                    <div className="flex items-center space-x-2 min-w-0">
                      <LogIcon className={`w-3.5 h-3.5 shrink-0 ${typeColor}`} />
                      <span className="text-zinc-600 shrink-0 font-light	">[{log.timestamp}]</span>
                      <span className="text-white truncate font-medium">{log.message}</span>
                    </div>
                    <div>
                      {log.data && (
                        isExpanded ? <ChevronUp className="w-3.5 h-3.5 text-zinc-550" /> : <ChevronDown className="w-3.5 h-3.5 text-zinc-550" />
                      )}
                    </div>
                  </div>

                  {isExpanded && log.data && (
                    <div className="bg-zinc-950 border-t border-zinc-900/60 p-2.5 mx-2 mb-2 text-[8.5px] leading-relaxed text-zinc-400 overflow-x-auto select-all max-w-full">
                      <pre className="whitespace-pre-wrap word-break">
                        {JSON.stringify(log.data, null, 2)}
                      </pre>
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
};
